### ISSUE TITLE
针对Neovim 使用Spacevim 的一些问题 

### ISSUE THREAD

**Issue by Aaronluoxiao** [Gabirel/Hack-SpaceVim#14]
由于本人刚使用Neovim，在 Neovim 安装SpaceVim遇到了一些问题，希望大神  解决。  
1 对于新手 需要一篇详细的 Neovim安装SpaceVim的教程
2 我安装成功之后   无法使用自动补全。后来发现 是Neovim 不支持lua   也不支持python 不知道怎么解决

**Comment by Gabirel** [comment]
你的操作系统？Windows/Linux还是Mac OS

**Comment by Aaronluoxiao** [comment]
windows

**Comment by Gabirel** [comment]
这对我们来说很困难，我们都不是很久很久不碰Windows的人，碰到了问题，我们都是一头雾水，这个可能要花点时间来弄了 :disappointed:

**Comment by Gabirel** [comment]
错误：pip install --user --upgrade neovim

```log
C:\Windows\system32>pip3 install neovim
Collecting neovim
  Using cached neovim-0.1.13.tar.gz
Requirement already satisfied: msgpack-python>=0.4.0 in c:\users\gabriel\appdata\roaming\python\python36\site-packages (from neovim)
Collecting pyuv>=1.0.0 (from neovim)
  Using cached pyuv-1.3.0.tar.gz
Collecting greenlet (from neovim)
  Using cached greenlet-0.4.12-cp36-cp36m-win_amd64.whl
Installing collected packages: pyuv, greenlet, neovim
  Running setup.py install for pyuv ... error
Exception:
Traceback (most recent call last):
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 9: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 9: invalid start byte
```

**Comment by Gabirel** [comment]
Reference: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

**Comment by Aaronluoxiao** [comment]
谢谢 已经阅读教程，配置成功了
